// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/mishasvintus/avito_backend_internship/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockTeamServiceInterface is an autogenerated mock type for the TeamServiceInterface type
type MockTeamServiceInterface struct {
	mock.Mock
}

type MockTeamServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamServiceInterface) EXPECT() *MockTeamServiceInterface_Expecter {
	return &MockTeamServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateTeam provides a mock function with given fields: teamName, members
func (_m *MockTeamServiceInterface) CreateTeam(teamName string, members []domain.TeamMember) error {
	ret := _m.Called(teamName, members)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []domain.TeamMember) error); ok {
		r0 = rf(teamName, members)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamServiceInterface_CreateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTeam'
type MockTeamServiceInterface_CreateTeam_Call struct {
	*mock.Call
}

// CreateTeam is a helper method to define mock.On call
//   - teamName string
//   - members []domain.TeamMember
func (_e *MockTeamServiceInterface_Expecter) CreateTeam(teamName interface{}, members interface{}) *MockTeamServiceInterface_CreateTeam_Call {
	return &MockTeamServiceInterface_CreateTeam_Call{Call: _e.mock.On("CreateTeam", teamName, members)}
}

func (_c *MockTeamServiceInterface_CreateTeam_Call) Run(run func(teamName string, members []domain.TeamMember)) *MockTeamServiceInterface_CreateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]domain.TeamMember))
	})
	return _c
}

func (_c *MockTeamServiceInterface_CreateTeam_Call) Return(_a0 error) *MockTeamServiceInterface_CreateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamServiceInterface_CreateTeam_Call) RunAndReturn(run func(string, []domain.TeamMember) error) *MockTeamServiceInterface_CreateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateTeam provides a mock function with given fields: teamName
func (_m *MockTeamServiceInterface) DeactivateTeam(teamName string) error {
	ret := _m.Called(teamName)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(teamName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTeamServiceInterface_DeactivateTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateTeam'
type MockTeamServiceInterface_DeactivateTeam_Call struct {
	*mock.Call
}

// DeactivateTeam is a helper method to define mock.On call
//   - teamName string
func (_e *MockTeamServiceInterface_Expecter) DeactivateTeam(teamName interface{}) *MockTeamServiceInterface_DeactivateTeam_Call {
	return &MockTeamServiceInterface_DeactivateTeam_Call{Call: _e.mock.On("DeactivateTeam", teamName)}
}

func (_c *MockTeamServiceInterface_DeactivateTeam_Call) Run(run func(teamName string)) *MockTeamServiceInterface_DeactivateTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTeamServiceInterface_DeactivateTeam_Call) Return(_a0 error) *MockTeamServiceInterface_DeactivateTeam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTeamServiceInterface_DeactivateTeam_Call) RunAndReturn(run func(string) error) *MockTeamServiceInterface_DeactivateTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function with given fields: teamName
func (_m *MockTeamServiceInterface) GetTeam(teamName string) (*domain.Team, error) {
	ret := _m.Called(teamName)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Team, error)); ok {
		return rf(teamName)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Team); ok {
		r0 = rf(teamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTeamServiceInterface_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamServiceInterface_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - teamName string
func (_e *MockTeamServiceInterface_Expecter) GetTeam(teamName interface{}) *MockTeamServiceInterface_GetTeam_Call {
	return &MockTeamServiceInterface_GetTeam_Call{Call: _e.mock.On("GetTeam", teamName)}
}

func (_c *MockTeamServiceInterface_GetTeam_Call) Run(run func(teamName string)) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTeamServiceInterface_GetTeam_Call) Return(_a0 *domain.Team, _a1 error) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTeamServiceInterface_GetTeam_Call) RunAndReturn(run func(string) (*domain.Team, error)) *MockTeamServiceInterface_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamServiceInterface creates a new instance of MockTeamServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamServiceInterface {
	mock := &MockTeamServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
